version: "3"
services:
  blog:
    environment:
      DJANGO_DEBUG: ""
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: jamie-blog
    ports:
      - "80:80"
    volumes:
      - ./settings.py:/home/blog/mysite/mysite/settings.py
      - ./urls.py:/home/blog/mysite/mysite/urls.py
      - ../jamie_blog:/home/blog/.local/lib/python3.9/site-packages/jamie_blog
      - ../test_articles:/home/blog/articles
      - ../test_wip:/home/blog/wip
    restart: always
    command: "python mysite/manage.py runserver 0.0.0.0:80"
volumes:
  wip: {}
