version: "3"
services:
  blog:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: jamie-blog
    volumes:
      - static:/home/blog/static
      - articles:/home/blog/articles
      - wip:/home/blog/wip
    restart: always
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
volumes:
  static: {}
  articles: {}
  wip: {}
